name: filesystem
version: 0.0.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=2.19.0 <3.0.0'
dependencies: 
  dcli: 2.0.1
  dcli_core: 2.0.1
dev_dependencies: 
  lint_hard: ^3.0.0
