name: dcli_test
description: Test code used by dcli - not for general use.
version: 4.0.1-alpha.6

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  dcli: ^4.0.1-alpha.6
  dcli_common: ^4.0.1-alpha.6
  dcli_core: ^4.0.1-alpha.6
  file: ^7.0.0
  meta: ^1.10.0
  path: ^1.8.3
  scope: ^4.1.0
  stack_trace: ^1.11.1
  test: ^1.24.7
  uuid: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
