name: dcli
version: 1.3.0
homepage: https://github.com/bsutton/dcli
description: An API and dev environment for writing console (cli) apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  archive: ^3.0.0
  args: ^2.0.0
  async: ^2.5.0
  collection: ^1.15.0
  crypto: ^3.0.0
  csv: ^5.0.0
  equatable: ^2.0.0
  file: ^6.1.0
  glob: ^2.0.0
  ini: ^2.1.0
  meta: ^1.3.0
  path: ^1.8.0
  pedantic: ^1.10.0
  posix: ^2.0.0
  pub_semver: ^2.0.0
  pubspec: ^2.0.0
  uuid: ^3.0.0
  validators2: ^3.0.0
  win32: ^2.1.0
  yaml: ^3.0.0
dev_dependencies: 
  hex: ^0.2.0
  lint: ^1.5.3
  mocktail: ^0.1.0
  settings_yaml: ^3.0.1
  test: ^1.0.0
executables: 
  dcli: dcli
  dcli_complete: dcli_complete
  dcli_install: dcli_install
  dshell_upgrade: dshell_upgrade
