name: dcli
version: 0.39.6
homepage: https://github.com/bsutton/dcli
description: An API and dev environment for writing console (cli) apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
environment: 
  sdk: '>=2.12.0-133.2.beta <3.0.0'
dependencies: 
  archive: ^2.0.13
  args: ^1.5.2
  async: ^2.5.0-nullsafety.3   
  collection: ^1.15.0-nullsafety.5 
  csv: ^4.0.3
  equatable: ^2.0.0-nullsafety.0   
  glob: ^1.2.0
  ini: ^2.0.1
  intl: ^0.17.0-nullsafety.2 
  logger: ^1.0.0-nullsafety.0    
  meta: ^1.3.0-nullsafety.6 
  path: ^1.7.0
  pedantic: ^1.10.0-nullsafety.3 
  pub_semver: ^1.4.2
  pubspec: ^0.1.5
  system_info: ^0.1.3
  uuid: ^2.0.4
  validators: ^2.0.0+1
  yaml: ^2.1.0 # ^3.0.0-nullsafety.0  
dev_dependencies: 
  effective_dart: ^1.0.0
  file: ^6.0.0-nullsafety.4  
  lint: ^1.0.0
  mockito: ^5.0.0-nullsafety.1  
  settings_yaml: ^2.1.0
  test: 1.16.0-nullsafety.13  
  # test_coverage: ^0.4.2
executables: 
  dcli: dcli
  dcli_complete: dcli_complete
  dcli_install: dcli_install
  dshell_upgrade: dshell_upgrade
