name: dshell
version: 1.8.7-dev.1
homepage: https://github.com/bsutton/dshell
description: An API and dev environment for writing console apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
environment: 
  sdk: '>=2.6.0 <3.0.0'
dependencies: 
  args: ^1.5.2
  collection: ^1.14.12
  csv: ^4.0.3
  equatable: ^1.0.1
  file: ^5.1.0
  file_utils: ^0.1.3
  glob: ^1.2.0
  ini: ^2.0.1
  intl: ^0.16.0
  logger: ^0.8.0
  meta: ^1.1.8
  mockito: ^4.0.0
  money2: ^1.0.5
  path: ^1.6.4
  pubspec: ^0.1.3
  pub_semver: ^1.4.2
  recase: ^3.0.0
  uuid: ^2.0.4
  yaml: ^2.2.0
dev_dependencies: 
  test: ^1.6.0
  pedantic: ^1.8.0
executables: 
  dshell: dshell
  dshell_complete: dshell_complete
  dshell_install: dshell_install
