name: dcli
version: 0.29.1
homepage: https://github.com/bsutton/dcli
description: An API and dev environment for writing console (cli) apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
environment: 
  sdk: '>=2.6.0 <3.0.0'
dependencies: 
  async: ^2.4.2
  archive: ^2.0.13
  args: ^1.5.2
  collection: ^1.14.12
  csv: ^4.0.3
  equatable: ^1.0.1
  ffi: ^0.1.3
  file: ^5.1.0
  glob: ^1.2.0
  ini: ^2.0.1
  intl: ^0.16.0
  logger: ^0.9.1
  meta: ^1.1.8
  path: ^1.7.0
  pedantic: ^1.6.0
  pub_semver: ^1.4.4
  system_info: ^0.1.3
  uuid: ^2.0.4
  validators: ^2.0.0+1
  yaml: ^2.2.0
  pubspec: ^0.1.5
dev_dependencies: 
  test: 1.15.3
  effective_dart: ^1.0.0
  mockito: ^4.0.0
  test_coverage: ^0.4.2
  settings_yaml: ^2.1.0
executables: 
  dcli: dcli
  dcli_complete: dcli_complete
  dcli_install: dcli_install
  dshell_upgrade: dshell_upgrade
