name: dcli
version: 1.14.1
homepage: https://dcli.noojee.dev
documentation: https://dcli.noojee.dev
description: An API and dev environment for writing console (cli) apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
repository: https://github.com/noojee/dcli
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  archive: ^3.0.0
  args: ^2.0.0
  async: ^2.5.0
  chunked_stream: ^1.4.1
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.0
  csv: ^5.0.1
  dart_console: ^1.0.0
  dcli_core: ^0.0.3
  equatable: ^2.0.0
  ffi: ^1.1.1
  file: ^6.1.0
  glob: ^2.0.0
  ini: ^2.1.0
  meta: ^1.3.0
  mime: ^1.0.1
  path: ^1.8.0
  posix: ^2.2.1
  pub_semver: ^2.0.0
  pubspec: ^2.0.0
  stacktrace_impl: ^2.2.1
  uuid: ^3.0.0
  validators2: ^3.0.0
  win32: ^2.1.0
  yaml: ^3.0.0
dev_dependencies: 
  hex: ^0.2.0
  lints: ^1.0.1
  mocktail: ^0.2.0
  settings_yaml: ^3.0.6
  test: ^1.0.0
executables: 
  dcli: dcli
  dcli_complete: dcli_complete
  dcli_install: dcli_install
  dshell_upgrade: dshell_upgrade
