name: dcli
version: 0.50.0-nullsaftey.1
homepage: https://github.com/bsutton/dcli
description: An API and dev environment for writing console (cli) apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
environment: 
  sdk: '>=2.12.0-259.9.beta <3.0.0'
dependencies: 
  archive: ^3.0.0
  args: ^2.0.0
  async: ^2.5.0
  collection: ^1.15.0
  csv: ^5.0.0-0
  equatable: ^2.0.0-nullsafety.3
  file: ^6.0.0
  glob: ^2.0.0
  ini: ^2.0.1
  intl: ^0.17.0
  logger: ^1.0.0-nullsafety.0
  meta: ^1.3.0
  path: ^1.8.0
  pedantic: ^1.10.0-nullsaftey
  posix: ^2.0.0-0
    
  pub_semver: ^2.0.0
  pubspec: #^0.1.5
    path: ../pubspec
  system_info: ^0.1.3
  uuid: ^3.0.0-nullsafety.1
  #validators: ^2.0.1
  yaml: ^3.0.0
dev_dependencies: 
  effective_dart: ^1.0.0
  lint: ^1.0.0
  mockito: ^5.0.0-nullsafety.1
  settings_yaml: ^3.0.0-0
  test: 1.16.2
executables: 
  dcli: dcli
  dcli_complete: dcli_complete
  dcli_install: dcli_install
  dshell_upgrade: dshell_upgrade