name: full
version: 0.0.1
publish_to: https://beta.onepub.dev/api/jbbxpsdavu/
description: A sample command-line application that installs and runs mailhog
environment: 
  sdk: '>=2.19.0-444.4.beta <3.0.0'
dependencies: 
  args: ^2.3.1
  dcli: ^2.0.0-beta.21
  dcli_core: ^2.0.0-beta.21
  http: ^0.13.4
  path: ^1.8.1
  settings_yaml: ^5.0.0-beta.1
dev_dependencies: 
  lint_hard: ^2.0.0
executables: 
  full: 
