name: console_simple
version: 0.0.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  dcli: ^2.0.0-beta.12
  dcli_core: ^2.0.0-beta.12
  lint_hard: ^2.0.0
