name: console_simple
version: 0.0.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  args: ^2.3.1
  dcli: ^3.0.1
  dcli_core: ^3.0.1
  lint_hard: ^3.0.0
