name: since
version: 0.0.1
description: A since command-line application created by dcli
environment: 
  sdk: '>=2.19.0 <4.0.0'
dependencies: 
  dcli: ^2.0.1
  stack_trace: ^1.10.0
dev_dependencies: 
  lint_hard: ^3.0.0
