name: dcli_terminal
version: 0.0.1-alpha.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=2.19.0 <3.0.0'
dependencies: 
  dart_console2: ^3.0.0-beta.1
  dcli: ^2.0.1
  dcli_core: ^2.0.1
dev_dependencies: 
  lint_hard: ^2.0.0
  test: ^1.23.1
