name: dcli_input
version: 0.0.1-alpha.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=2.19.0 <3.0.0'
dependencies: 
  dcli: 2.0.1
  dcli_core: 2.0.1
  dcli_terminal: 0.0.1-alpha.1
  meta: ^1.9.0
  validators2: ^4.0.0
dev_dependencies: 
  lint_hard: ^2.0.0
