name: console_simple
version: 0.0.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=2.19.0-444.4.beta <3.0.0'
dependencies: 
  dcli: ^2.0.0-beta.21
  dcli_core: ^2.0.0-beta.21
dev_dependencies: 
  lint_hard: ^2.0.0
