name: Release executables for Linux

on:
  push:
   
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Pub dependencies
      run: pub get
    - name: Compile installer
      run: 
        dart2native bin/dshell_install.dart -o bin/linux/dshell_install
    - name: Commit
      run: |
        git config --global user.email "bsutton@noojee.com.au"
        git config --global user.name "bsutton"
        git commit $GITHUB_WORKSPACE/bin/linux/dshell_install -m 'dart_install for linux' || echo "exec has not changed"
        git pull
        git push origin || echo "exec has not changed."
