name: Release executables for Linux

on:
  push:
    tags:
      - '*'
   
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: install pub_release
      # run: pub global activate pub_release
      run: pub global activate --source git https://github.com/bsutton/pub_release.git
    - name: Pub dependencies
      run: pub get
    - name: Create release
      env:
        APITOKEN:  ${{ secrets.APITOKEN }}
      run: git_release --username bsutton --apiToken "$APITOKEN" --owner bsutton --repository dcli --suffix linux-test 
