name: tool/run_unit_tests.dart

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install dependencies
      run: |
        pub get
        echo pwd
        echo $PWD
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        echo PATH=$PATH
        # find . 
        cd ..
        pwd
        apt update -y
        apt install -y procps ca-certificates gnupg2
       
    - name: activate dcli
      run: |
        ls
        cd ..
        pwd
        pub global activate dcli --source path
        # dart ./tool/activate_local.dart --path=. 
        
    - name: install dcli
      run: |
        echo $PWD
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        echo $PATH
        ls "$HOME/.pub-cache/bin"
        dcli install
                
        
    - name: Run pubspec_default_tesets
      run: |
        pwd
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        pub run test/src/pubspec/pubspec_default_test.dart
        
    #- name: Run tests
     # run: |
      #  dart ./tool/run_unit_tests.dart
