name: tool/run_unit_tests.dart

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pub get
        echo pwd
        echo $PWD
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        echo PATH=$PATH
        # find . 
        cd ..
        pwd
        ls
        pub global activate dshell --source path
        # dart ./tool/activate_local.dart --path=. 
        pwd
        dshell_install
        cd dshell
        pwd
        
    - name: Run tests
      run: |
        dart ./tool/run_unit_tests.dart
