name: tool/run_unit_tests.dart

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: echo pwd
      run: echo $PWD
    - name: show files
      run: find . -name "*.dart"
    - name: complete dshell install
      run: dart ./bin/dshell.dart install
    - name: Run tests
      run: ./tool/run_unit_tests.dart
