name: Release executables for Windows

on:
  push:
   
jobs:
  build:

    runs-on: windows-latest

    #container:
     # image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch Dart SDK
      run: curl https://storage.googleapis.com/dart-archive/channels/stable/release/2.8.4/sdk/dartsdk-windows-x64-release.zip -o dartsdk.zip 
    - name: Extract Dart sDK
      run: tar.exe -xf dartsdk.zip
    - name: Pub get
      run: dart-sdk/bin/pub.bat get
    - name: Compile Installer
      run: dart-sdk/bin/dart2native.bat bin/dshell_install.dart -o bin/windows/dshell_install.exe
    - name: commit changes
      run: |
        git config --global user.email "bsutton@noojee.com.au"
        git config --global user.name "bsutton"
        git commit bin/windows/dshell_install.exe -m 'dart_install.exe for windows' || echo "exec has not changed"
        git pull
        git push origin || echo "exec has not changed."
